name: Build Container for Staging & Push to Dockerhub

on:
  push:
    branches:
      - 'dev'

jobs:
  build-and-deploy-frontend:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        dockerfile: REIOPCENTER--VUE-RONT-END/Dockerfile
        tags: reiopcenter/vue-frontend:latest